# Generated by Django 3.0.5 on 2020-05-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('max_time', models.IntegerField(default=600)),
                ('min_views', models.IntegerField(default=5)),
                ('allow_concurrent', models.BooleanField(default=True)),
                ('gamma', models.FloatField(default=5.0)),
                ('epsilon', models.FloatField(default=0.25)),
            ],
        ),
    ]
