# Generated by Django 3.0.5 on 2020-05-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='max_time',
            field=models.PositiveSmallIntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='survey',
            name='min_views',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
