# Generated by Django 3.0.5 on 2020-05-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_survey_trust_annotators'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='gamma',
            new_name='base_gamma',
        ),
        migrations.AddField(
            model_name='survey',
            name='dynamic_gamma',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='max_budget',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='survey',
            name='min_budget',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='survey',
            name='tau',
            field=models.FloatField(default=0.25),
        ),
        migrations.AlterField(
            model_name='survey',
            name='max_items',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
