# Generated by Django 3.0.5 on 2020-05-02 05:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_survey_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=1),
            preserve_default=False,
        ),
    ]
