# Generated by Django 3.0.5 on 2020-05-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20200502_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='max_annotators',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='survey',
            name='max_items',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
