# Generated by Django 3.0.5 on 2020-05-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20200509_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='max_annotators',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='survey',
            name='max_budget',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='survey',
            name='min_budget',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
