# Generated by Django 3.0.5 on 2020-05-02 02:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotators', '0002_auto_20200502_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotator',
            name='Metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
    ]
