# Generated by Django 3.0.5 on 2020-05-02 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('annotators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotator',
            name='current',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_annotators', to='items.Item'),
        ),
        migrations.AlterField(
            model_name='annotator',
            name='previous',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_annotators', to='items.Item'),
        ),
    ]
