# Generated by Django 3.0.5 on 2020-05-02 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotators', '0003_annotator_metadata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotator',
            old_name='Metadata',
            new_name='metadata',
        ),
    ]
