# Generated by Django 3.0.5 on 2020-05-02 19:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotators', '0004_auto_20200502_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotator',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
