version: '3.7'
services:
  traefik:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  backend:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  frontend:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  celery_worker:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  redis-exporter:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
