version: "3.7"
services:
  traefik:
    secrets:
      - traefik_users
      - prometheus_users
  backend:
    secrets:
      - DJANGO_SECRETS
      - SOCIAL_PROVIDER_SECRETS
  frontend:
    secrets:
      - FRONTEND_SECRETS
      - SOCIAL_PROVIDER_SECRETS
  celery_worker:
    secrets:
      - DJANGO_SECRETS
      - SOCIAL_PROVIDER_SECRETS
  grafana:
    secrets:
      - grafana_password

secrets:
  traefik_users:
    file: ../traefik_users
  DJANGO_SECRETS:
    file: ../django.secrets
  FRONTEND_SECRETS:
    file: ../frontend.secrets
  SOCIAL_PROVIDER_SECRETS:
    file: ../social-provider.secrets
  grafana_password:
    file: ../grafana_password
  prometheus_users:
    file: ../prometheus_users
