version: "3.7"
services:
  traefik:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../acme.json:/acme.json
      - ../.htpasswd:/.htpasswd
  postgres:
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
      - postgres_backups:/backups
  mongo:
    volumes:
      - mongo_data:/bitnami/mongodb
volumes:
  postgres_data:
  postgres_backups:
  mongo_data:
