version: "3.7"
services:
  backend:
    networks:
      - default
      - proxy
  traefik:
    networks:
      - default
      - proxy
  celery_worker:
    networks:
      - default
  postgres:
    networks:
      - default
  redis:
    networks:
      - default
  grafana:
    networks:
      - default
      - proxy
  portainer:
    networks:
      - default
      - proxy
  exporter:
    networks:
      - default
  prometheus:
    networks:
      - default

networks:
  default:
  proxy:
    external: true
