version: '3.7'
services:
  backend:
    volumes:
      - ../django.secrets:/DJANGO_SECRETS
      - ../social-provider.secrets:/SOCIAL_PROVIDER_SECRETS
      - ../backend:/app
  celery_worker:
    volumes:
      - ../django.secrets:/DJANGO_SECRETS
      - ../social-provider.secrets:/SOCIAL_PROVIDER_SECRETS
      - ../backend:/app
  frontend:
    volumes:
      - frontend_node_modules:/app/node_modules
      - ../frontend.secrets:/FRONTEND_SECRETS
      - ../social-provider.secrets:/SOCIAL_PROVIDER_SECRETS
      - ../frontend:/app

volumes:
  frontend_node_modules:
