version: "3.7"
services:
  backend:
    depends_on:
      - postgres
      - redis
  celery_worker:
    depends_on:
      - postgres
      - redis
      - backend
  frontend:
    depends_on:
      - mongo
