version: '3.7'
services:
  traefik:
    command: >
      --providers.docker
      --providers.docker.swarmMode=true
      --providers.docker.exposedbydefault=false
      --providers.docker.network=proxy
      --accesslog=true
      --metrics.prometheus=true
      --api.dashboard=true
      --entrypoints.web.address=:80
      --entrypoints.websecure.address=:443
      --certificatesResolvers.le.acme.email=${EMAIL}
      --certificatesResolvers.le.acme.storage=acme.json
      --certificatesResolvers.le.acme.httpChallenge=true
      --certificatesResolvers.le.acme.httpChallenge.entryPoint=web
  backend:
    command: gunicorn backend.asgi:application --config gunicorn.conf.py
  frontend:
    command: yarn start
  redis-exporter:
    command: --redis.addr=redis://redis:6379
