version: '3.7'
services:
  backend:
    environment:
      - DEBUG=True
      - SECRETS_PATH=/
  celery_worker:
    environment:
      - DEBUG=True
      - SECRETS_PATH=/
  frontend:
    environment:
      - SECRETS_PATH=/
      - API_URL=http://frontend:3000
      - API_URL_BROWSER=http://localhost
