version: '3.7'
services:
  backend:
    environment:
      - DEBUG=False
      - USE_SSL=True
      - SECRETS_PATH=/run/secrets
      - prometheus_multiproc_dir=/prometheus_tmp
  celery_worker:
    environment:
      - DEBUG=False
      - SECRETS_PATH=/run/secrets
  frontend:
    environment:
      - SECRETS_PATH=/run/secrets
      - API_URL=http://backend:8000
      - API_URL_BROWSER=https://api.${DOMAIN}
  grafana:
    environment:
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/grafana_password
